# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g yo
    npm link
  displayName: 'npm install'

- script: |
    yo ansible-project -help
  displayName: 'Execute yo ansible-project'

- task: Npm@1
  inputs:
     command: publish
     publishRegistry: useFeed
     publishFeed: npm-local
  displayName: 'publish packages'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'generator-ansible-project'
    targetPath: $(System.DefaultWorkingDirectory)  
